import { fetchGalleryItems } from "/js/services/gallery-data.js";

const elements = { filters: document.querySelector("#galleryFilters"), clear: document.querySelector("#clearFilters"), grid: document.querySelector("#galleryPageGrid"), count: document.querySelector("#galleryResultCount"), dialog: document.querySelector("#galleryLightbox"), image: document.querySelector("#lightboxImage"), caption: document.querySelector("#lightboxCaption"), close: document.querySelector("#lightboxClose"), prev: document.querySelector("#lightboxPrev"), next: document.querySelector("#lightboxNext") };
let allItems=[]; let visibleItems=[]; let activeCategories=new Set(); let currentIndex=0;
function escapeText(value){ return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); }
function renderFilters(){ const categories=[...new Set(allItems.flatMap(item=>item.category||[]))].sort((a,b)=>a.localeCompare(b,"zh-Hant")); elements.filters.innerHTML=categories.map(category=>`<button class="filter-chip" type="button" data-category="${escapeText(category)}" aria-pressed="false">${escapeText(category)}</button>`).join(""); }
function renderItems(){ visibleItems=allItems.filter(item=>!activeCategories.size || [...activeCategories].every(category=>(item.category||[]).includes(category))); elements.count.textContent=`共 ${visibleItems.length} 件作品`; if(!visibleItems.length){ elements.grid.innerHTML='<p class="gallery-empty">目前沒有符合所選分類的作品。</p>'; return; } elements.grid.innerHTML=visibleItems.map((item,index)=>`<button class="gallery-work" id="work-${escapeText(item.id)}" type="button" data-index="${index}"><img src="${escapeText(item.image)}" alt="${escapeText(item.title||'美甲作品')}" loading="lazy" /><span class="gallery-work-info"><span class="gallery-work-title">${escapeText(item.title||'美甲作品')}</span><span class="gallery-work-meta">${escapeText((item.category||[]).join('・'))}</span></span></button>`).join(""); }
function openLightbox(index){ currentIndex=index; const item=visibleItems[index]; if(!item)return; elements.image.src=item.image; elements.image.alt=item.title||"美甲作品"; elements.caption.textContent=[item.title,(item.category||[]).join("・")].filter(Boolean).join("｜"); if(!elements.dialog.open)elements.dialog.showModal(); }
function move(step){ if(!visibleItems.length)return; openLightbox((currentIndex+step+visibleItems.length)%visibleItems.length); }
elements.filters.addEventListener("click",event=>{ const button=event.target.closest("[data-category]"); if(!button)return; const category=button.dataset.category; activeCategories.has(category)?activeCategories.delete(category):activeCategories.add(category); button.classList.toggle("is-active",activeCategories.has(category)); button.setAttribute("aria-pressed",String(activeCategories.has(category))); renderItems(); });
elements.clear.addEventListener("click",()=>{ activeCategories.clear(); elements.filters.querySelectorAll(".filter-chip").forEach(button=>{button.classList.remove("is-active");button.setAttribute("aria-pressed","false");});renderItems();});
elements.grid.addEventListener("click",event=>{const button=event.target.closest("[data-index]");if(button)openLightbox(Number(button.dataset.index));}); elements.close.addEventListener("click",()=>elements.dialog.close()); elements.prev.addEventListener("click",()=>move(-1)); elements.next.addEventListener("click",()=>move(1)); elements.dialog.addEventListener("click",event=>{if(event.target===elements.dialog)elements.dialog.close();}); document.addEventListener("keydown",event=>{if(!elements.dialog.open)return;if(event.key==="ArrowLeft")move(-1);if(event.key==="ArrowRight")move(1);});
try { allItems=await fetchGalleryItems(); renderFilters(); renderItems(); const target=location.hash.slice(6); if(target){ const index=visibleItems.findIndex(item=>item.id===decodeURIComponent(target)); if(index>=0)openLightbox(index); } } catch(error){ elements.grid.innerHTML=`<p class="gallery-empty">作品載入失敗：${escapeText(error.message)}</p>`; }
