const API_URL="/api/admin/gallery";
const DEFAULT_CATEGORIES=["單色","漸層","法式","暈染","手繪","貓眼","新娘","足部","其他"];
const elements={list:document.querySelector("#galleryAdminList"),create:document.querySelector("#createGalleryButton"),filter:document.querySelector("#galleryStatusFilter"),dialog:document.querySelector("#galleryDialog"),form:document.querySelector("#galleryForm"),editorTitle:document.querySelector("#galleryEditorTitle"),close:document.querySelector("#closeGalleryDialog"),cancel:document.querySelector("#cancelGalleryButton"),save:document.querySelector("#saveGalleryButton"),message:document.querySelector("#galleryFormMessage"),categories:document.querySelector("#galleryCategoryOptions"),custom:document.querySelector("#customGalleryCategories")};
let items=[];let loaded=false;
function escapeText(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
async function request(url,options={}){const response=await fetch(url,{cache:"no-store",...options});if(!response.ok){let message=`HTTP ${response.status}`;try{const data=await response.json();message=data.error||message;}catch{}throw new Error(message);}return response.status===204?null:response.json();}
function allCategories(){return [...new Set([...DEFAULT_CATEGORIES,...items.flatMap(item=>item.category||[])])];}
function renderCategoryOptions(selected=[]){elements.categories.innerHTML=allCategories().map(category=>`<label class="category-option"><input type="checkbox" name="category" value="${escapeText(category)}" ${selected.includes(category)?"checked":""}/><span>${escapeText(category)}</span></label>`).join("");}
function filteredItems(){const value=elements.filter.value;return items.filter(item=>value==="all"||(value==="featured"&&item.featured)||(value==="active"&&item.isActive)||(value==="hidden"&&!item.isActive));}
function render(){const visible=filteredItems();if(!visible.length){elements.list.innerHTML='<p class="empty-message">目前沒有符合條件的作品。</p>';return;}elements.list.innerHTML=visible.map(item=>`<article class="gallery-admin-item"><div class="gallery-admin-thumb"><img src="${escapeText(item.image)}" alt="" /></div><div class="promotion-info"><h3>${escapeText(item.title||"未命名作品")}</h3><div class="promotion-meta"><span class="status-chip ${item.isActive?"":"is-hidden"}">${item.isActive?"公開中":"已隱藏"}</span>${item.featured?"<span>⭐ 精選</span>":""}<span>${escapeText((item.category||[]).join("・")||"未分類")}</span><span>${escapeText(item.date||"")}</span><span>排序 ${item.sortOrder??0}</span></div></div><div class="promotion-actions"><button class="button" type="button" data-gallery-action="edit" data-id="${item.id}">編輯</button><button class="button" type="button" data-gallery-action="toggle" data-id="${item.id}">${item.isActive?"隱藏":"顯示"}</button><button class="button button-danger" type="button" data-gallery-action="delete" data-id="${item.id}">刪除</button></div></article>`).join("");}
async function load(){elements.list.innerHTML='<p class="empty-message">作品資料載入中...</p>';const data=await request(`${API_URL}?t=${Date.now()}`);items=data.items||[];loaded=true;render();}
function set(name,value){const field=elements.form.elements.namedItem(name);if(!field)return;if(field.type==="checkbox")field.checked=Boolean(value);else field.value=value??"";}
function openEditor(item=null){elements.form.reset();elements.message.textContent="";elements.editorTitle.textContent=item?"編輯作品":"上傳作品";set("date",new Date().toISOString().slice(0,10));set("sortOrder",0);set("artistId","default");set("isActive",true);if(item){["id","title","date","sortOrder","artistId","isActive","featured"].forEach(name=>set(name,item[name]));}renderCategoryOptions(item?.category||[]);elements.custom.value="";elements.dialog.showModal();}
function close(){elements.dialog.close();}
function collectCategories(){const checked=[...elements.categories.querySelectorAll('input[name="category"]:checked')].map(input=>input.value);const custom=elements.custom.value.split(/[,，]/).map(value=>value.trim()).filter(Boolean);return [...new Set([...checked,...custom])];}
async function save(event){event.preventDefault();elements.message.textContent="";elements.save.disabled=true;elements.save.textContent="儲存中...";try{const formData=new FormData(elements.form);formData.delete("category");collectCategories().forEach(category=>formData.append("category",category));formData.set("isActive",String(elements.form.isActive.checked));formData.set("featured",String(elements.form.featured.checked));const id=formData.get("id");if(!id&&!formData.get("image")?.size)throw new Error("新增作品時必須選擇圖片。");await request(id?`${API_URL}/${encodeURIComponent(id)}`:API_URL,{method:id?"PUT":"POST",body:formData});close();await load();}catch(error){elements.message.textContent=`儲存失敗：${error.message}`;}finally{elements.save.disabled=false;elements.save.textContent="儲存作品";}}
async function action(event){const button=event.target.closest("[data-gallery-action]");if(!button)return;const item=items.find(value=>value.id===button.dataset.id);if(!item)return;if(button.dataset.galleryAction==="edit"){openEditor(item);return;}if(button.dataset.galleryAction==="toggle"){const formData=new FormData();Object.entries({...item,isActive:!item.isActive}).forEach(([key,value])=>{if(key==="category"){value.forEach(category=>formData.append("category",category));}else if(value!==null&&value!==undefined)formData.set(key,String(value));});await request(`${API_URL}/${encodeURIComponent(item.id)}`,{method:"PUT",body:formData});await load();return;}if(button.dataset.galleryAction==="delete"){if(!confirm(`確定刪除「${item.title||"此作品"}」嗎？圖片也會一併刪除。`))return;await request(`${API_URL}/${encodeURIComponent(item.id)}`,{method:"DELETE"});await load();}}
export function initializeGalleryAdmin(){elements.create.addEventListener("click",()=>openEditor());elements.filter.addEventListener("change",render);elements.close.addEventListener("click",close);elements.cancel.addEventListener("click",close);elements.form.addEventListener("submit",save);elements.list.addEventListener("click",event=>action(event).catch(error=>alert(`操作失敗：${error.message}`)));}
export async function ensureGalleryLoaded(){if(!loaded)await load();}
