const METADATA_KEY="gallery/metadata/gallery.json";
export function jsonResponse(data,status=200){return Response.json(data,{status,headers:{"Cache-Control":"no-store"}});}
export function toBoolean(value){return value===true||value==="true"||value==="1"||value===1;}
export async function readGallery(env){const object=await env.GALLERY_ASSETS.get(METADATA_KEY);if(!object)return {version:1,items:[]};try{const data=await object.json();return {version:Number(data.version||1),items:Array.isArray(data.items)?data.items:[]};}catch{return {version:1,items:[]};}}
export async function writeGallery(env,data){await env.GALLERY_ASSETS.put(METADATA_KEY,JSON.stringify(data,null,2),{httpMetadata:{contentType:"application/json",cacheControl:"no-store"}});}
export function createGalleryId(){return `work-${Date.now()}-${crypto.randomUUID().slice(0,8)}`;}
export function readGalleryForm(formData,existing={}){const categories=formData.getAll("category").filter(value=>typeof value==="string").map(value=>value.trim()).filter(Boolean);return {title:String(formData.get("title")??existing.title??"").trim(),category:categories.length?categories:(existing.category||[]),featured:toBoolean(formData.get("featured")),isActive:toBoolean(formData.get("isActive")),date:String(formData.get("date")??existing.date??new Date().toISOString().slice(0,10)).trim(),sortOrder:Number.parseInt(String(formData.get("sortOrder")??existing.sortOrder??0),10)||0,artistId:String(formData.get("artistId")??existing.artistId??"default").trim()||"default"};}
export async function uploadGalleryImage(env,file,id){if(!(file instanceof File)||file.size===0)return null;const allowed=new Set(["image/jpeg","image/png","image/webp"]);if(!allowed.has(file.type))throw new Error("作品圖片僅支援 JPG、PNG 或 WebP。");if(file.size>12*1024*1024)throw new Error("單張作品圖片不可超過 12 MB。");const ext={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"}[file.type];const key=`gallery/images/${id}/${Date.now()}.${ext}`;await env.GALLERY_ASSETS.put(key,file.stream(),{httpMetadata:{contentType:file.type,cacheControl:"public, max-age=31536000, immutable"}});return {key,url:`/api/gallery-media/${key}`};}
export function sortGallery(items){return [...items].sort((a,b)=>(Number(a.sortOrder||0)-Number(b.sortOrder||0))||String(b.date||"").localeCompare(String(a.date||""))||String(b.createdAt||"").localeCompare(String(a.createdAt||"")));}
